name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]
        python-version: [3.6.x, 3.7.x, 3.8.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install Cython numpy wheel setuptools
      - name: Build wheel package
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload wheel package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_${{ matrix.python-version}}.whl
          path: dist/d3rlpy-*.whl
          retention-days: 5
