name: format check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python.3.7.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.x
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black mypy pylint
      - name: Check format
        run: |
          ./scripts/format --check

      - name: Linter
        run: |
          ./scripts/lint
