name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python.3.6.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.10
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest gym
      - name: Unit tests
        run: |
          ./test
